repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@2.3.2"]
        files: \.(json|js|md|yaml|yml)$
