<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>fileTypes</key>
	<array>
		<string>bend</string>
	</array>
	<key>name</key>
	<string>bend</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#reserved-words</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator-dedicated-keywords-statements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ctrl-statements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#true-false</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#customs</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>end</key>
					<string>
</string>
					<key>name</key>
					<string>comment.line.double-dash.bend</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>
</string>
					<key>name</key>
					<string>comment.line.double-dash.bend</string>
				</dict>
			</array>
		</dict>
		<key>customs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bdata\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\blet\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bSome\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s*\.)\w+</string>
					<key>name</key>
					<string>support.variable.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+(?=\s*=)</string>
					<key>name</key>
					<string>support.variable.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bbend\s)\w+</string>
					<key>name</key>
					<string>support.variable.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bdef\s)\w+</string>
					<key>name</key>
					<string>support.function.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bobject\s)\w+</string>
					<key>name</key>
					<string>support.other.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bfold\s)\w+</string>
					<key>name</key>
					<string>support.type.property-name.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bopen\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bdo\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\bidentity\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\blambda\s)\w+</string>
					<key>name</key>
					<string>support.class.bend</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[a-zA-Z]+\s*\(</string>
					<key>name</key>
					<string>support.function.bend</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+\.\d+\b</string>
					<key>name</key>
					<string>constant.numeric.bend</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d{1,3}(?:_\d{3})*\b</string>
					<key>name</key>
					<string>constant.numeric.bend</string>
				</dict>
			</array>
		</dict>
		<key>operator-dedicated-keywords-statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(bend|None|Nil|Result|type)\b</string>
					<key>name</key>
					<string>keyword.bend</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(\+|-|\*|/|!)\b</string>
					<key>name</key>
					<string>keyword.operator.new.bend</string>
				</dict>
			</array>
		</dict>
		<key>reserved-words</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Node|Leaf|Tree)\b</string>
					<key>name</key>
					<string>support.type.bend</string>
				</dict>
			</array>
		</dict>
		<key>special-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(def|switch|case|return|if|else|when|match|λ|Some|data|let|use|object|fold|open|do|bind|Name|identity|Bool|ask|with)\b</string>
					<key>name</key>
					<string>keyword.control.less.bend</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.bend</string>
				</dict>
			</array>
		</dict>
		<key>true-false</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(True|False)\b</string>
					<key>name</key>
					<string>keyword.operator.new.bend</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bend</string>
</dict>
</plist>
